### ISSUE TITLE
Change address on send page

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#10]

**Comment by sinaizd** [comment]
When changing outgoing address we need to display "MY ACTIVE ADDRESSES" list.
design:
https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5e31937ce950ee9641b9d36a
![image](https://user-images.githubusercontent.com/45556620/79862563-f2573000-83de-11ea-8ea4-3b9c93e9f6e9.png)
Actua: when click "change" just changes the address.

**Comment by iscander01** [comment]
not relevant
