### ISSUE TITLE
After sending transaction wallet creates two address in address book

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#113]
Pre-conditions:
There is actual token 
Steps to reproduce:
1. Open Send screen and paste token
2. Remember Outgoing address
![Snag_1e4d733](https://user-images.githubusercontent.com/51320829/81419344-c9f96080-9156-11ea-8c7c-b66e32044228.png)
3. Sent transaction
4. Open Addresses book
Expected: Transaction sent from this address
Actual: Transaction sent from another auto-generated address
![Snag_1e581fa](https://user-images.githubusercontent.com/51320829/81419422-e39aa800-9156-11ea-8693-b2460a98806e.png)

**Comment by iscander01** [comment]
not relevant
