### ISSUE TITLE
QR-code hasn't been recognised

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#116]
There is no code after scanning
![Snag_10f9e3d](https://user-images.githubusercontent.com/51320829/81552798-c7804c00-938c-11ea-9382-71308029c007.png)

**Comment by VladislavKulyba** [comment]
1. After adding comment or amount on receiver screen token is changed to another, and after few seconds changed to first state. (also the same behaviour foe QR-code)
 [2020-05-13_12-13-57.zip](https://github.com/BeamMW/web-wallet/files/4622519/2020-05-13_12-13-57.zip)


2. If receiver adds amount to token and send token to sender, after pasting token on sender screen amount wouldn't be shown automatically on sender side.

**Comment by VladislavKulyba** [comment]
2. it's task #132

**Comment by VladislavKulyba** [comment]
Checked

**Comment by VladislavKulyba** [comment]
Android beam wallet doesn't recognise QR code. 
Tested on masternet

**Comment by VladislavKulyba** [comment]
Not relevant

**Comment by Roberrtt** [comment]
After adding a comment, the Qr code changes

**Comment by Roberrtt** [comment]
checked
