### ISSUE TITLE
Waiting for receiver status changes to failed after re-login 

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#123]
Pre-conditions:
There is web wallet and cli wallet are running
Steps to reproduce:
1. Create token in cli wallet. 
2. Check that CLI wallet is not running (or stop it)
3. Paste token in Web Wallet and send some amount. Transaction has "waiting for receiver" status
4. Logout from Web Wallet
5. Refresh page and login to Web Wallet. Transaction still has "waiting for receiver" status
6. Listen on CLI wallet 

Expected: "waiting for receiver" status was changed to "sending". Transaction is successful
Actual: "waiting for receiver" status was changed to "failed". Transaction is failed.

**Comment by chapati** [comment]
This is a problem not at service side.
An empty identity is passed in amountUpdated() method of the receiver component

**Comment by chapati** [comment]
Now transactions are cancelled on relogin.

**Need to implement:**

1. params: {fresh_keeper: true/false} on wallet open as we have discussed

3. Show message to the use on logout/close similar to what we have in the UI wallet

![11](https://user-images.githubusercontent.com/12074933/85337647-87fb6280-b4e9-11ea-99de-3b60689feef9.png)

Text should be: "There are N transaction that might be cancelled or fail if the wallet goes offline. Are you sure to close the wallet now?"

Please not that not all transactions should be cancelled, only those which have `status` less than `3`. Do not show this message if there are no transactions to cancel.

**Comment by iscander01** [comment]
1. done
2. cannot be done with extension popup view

**Comment by VladislavKulyba** [comment]
> 1. done
> 2. cannot be done with extension popup view

Checked according to this. Need to find a solution with error message in extension view in next sprint
