### ISSUE TITLE
Web Wallet: get amount from token

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#132]
Need to add method to the keeper to get amount ​​from existing token

**Comment by VladislavKulyba** [comment]
Transactions with such generated token are failed with error 'Aborted by the user'
![Snag_1411a35](https://user-images.githubusercontent.com/51320829/84265735-f7597580-ab2b-11ea-8eff-50551badb009.png)

Steps to reproduce:
1. Go to receiver screen in web wallet
2. Write any amount in according field (23, for example)
3. Copy token with this amount
4. Open UI Wallet and paste token to Send screen
5. Token was pasted with appropriate amount (in this case 23)
6. Doesn't change amount and press send

Expected: Transaction with 23 beams a successfully sent
Actual: Transaction was failed immediately with error 'Aborted by the user'

log 
[beam_ui_20_06_10_12_21_56.log](https://github.com/BeamMW/web-wallet/files/4758299/beam_ui_20_06_10_12_21_56.log)
tx_Id 869a18a654d045e594a0ffd276a7879e
[2020-06-10_15-03-03.zip](https://github.com/BeamMW/web-wallet/files/4758307/2020-06-10_15-03-03.zip)
example:
[2020-06-10_15-03-03.zip](https://github.com/BeamMW/web-wallet/files/4758314/2020-06-10_15-03-03.zip)

**Comment by chapati** [comment]
This is a problem not at service side. Should be fixed in the web wallet js code.
An empty identity is passed in amountUpdated() method of the receiver component

**Comment by VladislavKulyba** [comment]
checked
