### ISSUE TITLE
Indicator "beta version" + restore doesn't support

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#133]
Please add line to the top on all screens: https://zpl.io/VDdWj6l

![image](https://user-images.githubusercontent.com/47353570/84360214-6f7a7680-abd2-11ea-9873-2a3eb9195c03.png)

On login screens please add text "Restore is not supported in this Beta version." under the button: https://zpl.io/bzR7Qll
![image](https://user-images.githubusercontent.com/47353570/84360327-92a52600-abd2-11ea-813d-778ee19964ee.png)

The same for full version:
https://zpl.io/beJx74D
https://zpl.io/aXAndrx

**Comment by sasha-abramovich** [comment]
@dariatarakanova @iscander01 "Restore is not supported in this Beta version".

**Comment by VladislavKulyba** [comment]
please add text "Restore is not supported in this Beta version." under the 'open your wallet' button 
![Snag_197c4a](https://user-images.githubusercontent.com/51320829/85289815-ad17b300-b4a0-11ea-87aa-a8f9a0ee2e5f.png)

**Comment by VladislavKulyba** [comment]
checked
