### ISSUE TITLE
Show owner key

### ISSUE THREAD

**Issue by chapati** [BeamMW/web-wallet-angular#135]
Need to add an option to show owner key. The same as in the GUI wallet.

**Comment by VladislavKulyba** [comment]
first popup: 
1. Fix mistake in popup name (owner)
2. Change icon and button name as it's done in desktop
![image](https://user-images.githubusercontent.com/51320829/86583146-75723600-bf8b-11ea-8a7d-b46879f70b1f.png)


second popup:
1. Change 'cancel' to 'close'
2. Change 'ok' button to 'copy'
3. Add appropriate text in ths popup
4. Fix name of this popup to 'Owner key'
![image](https://user-images.githubusercontent.com/51320829/86583417-e44f8f00-bf8b-11ea-897b-897a39cb89bf.png)

**Comment by VladislavKulyba** [comment]
isn't relevant
