### ISSUE TITLE
Error on wallet creation

### ISSUE THREAD

**Issue by chapati** [BeamMW/web-wallet-angular#138]
Need to show error when wallet create fails. For example it is what happens now if duplicate seed phrase is used:

![gnome-shell-screenshot-3D9NM0](https://user-images.githubusercontent.com/12074933/85335245-58e2f200-b4e5-11ea-926b-e9bcf90c8f28.png)

I'll add a separate error code for this situation. There might be also connectivity issues, server might be down &c.

**Comment by chapati** [comment]
Server down.

![gnome-shell-screenshot-IHSRM0](https://user-images.githubusercontent.com/12074933/85335376-96477f80-b4e5-11ea-8fc0-36d9f7d9e69e.png)

**Comment by VladislavKulyba** [comment]
> Server down.
> 
> ![gnome-shell-screenshot-IHSRM0](https://user-images.githubusercontent.com/12074933/85335376-96477f80-b4e5-11ea-8fc0-36d9f7d9e69e.png)

checked
