### ISSUE TITLE
Add some functionality while wallet is loading

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#146]
Sometimes there are situations when wallet doesn't open immediately after log in. The user won't understand if wallet is loading or not. We need to shown some loader or loading page after log in to wallet, as it was done for mobile. 

![Snag_8a7e3c2](https://user-images.githubusercontent.com/51320829/87041851-83c68900-c1fb-11ea-8437-bc3d8f70fa96.png)

@gingervik @sasha-abramovich Please, decide how it will display.

**Comment by sasha-abramovich** [comment]
Following the talk with @chapati, "Loading wallet data" is a good message to write above the loader.

**Comment by Sergei-Beam** [comment]
checked
