### ISSUE TITLE
Change amount color for some statuses

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#148]
How it displays right now:

![image](https://user-images.githubusercontent.com/51320829/87146824-378b4f80-c2b4-11ea-9dd2-c40866884ceb.png)

Please, change the appropriate amount color for failed, expired, and canceled transactions. A user should understand if it's an incoming or outgoing transaction. For example, as it's been done for Desktop wallet for the expired transaction

![Snag_ade9d9](https://user-images.githubusercontent.com/51320829/87146589-dcf1f380-c2b3-11ea-90eb-e5058b4879d4.png)

**Comment by Roberrtt** [comment]
Recheck after this task https://github.com/BeamMW/web-wallet/issues/179

**Comment by Roberrtt** [comment]
The amount is highlighted in red if the transaction has the failed status
![Screenshot_321](https://user-images.githubusercontent.com/50007056/122347465-ba03a100-cf52-11eb-9208-3a1e878ed6c7.png)

**Comment by Roberrtt** [comment]
Also the expired status, it should be gray and the amount in accordance with receive(blue)\send(pink)
![Screenshot_327](https://user-images.githubusercontent.com/50007056/122365347-4322d400-cf63-11eb-8c3c-0a709b12eb2b.png)

**Comment by Roberrtt** [comment]
Change the color to gray for the "expired" status
![Screenshot_354](https://user-images.githubusercontent.com/50007056/122773778-4db9d200-d2b1-11eb-9b57-3dd0333bc434.png)

**Comment by Roberrtt** [comment]
checked
