### ISSUE TITLE
Replace "Scalable confidential cryptocurrency" to "Confidential, fast, easy to use" 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#149]
Replace "Scalable confidential cryptocurrency" to "Confidential, fast, easy to use" on each page where it appears

![image](https://user-images.githubusercontent.com/47353570/87149831-a5864580-c2b9-11ea-8037-ac060d53e5a0.png)

**Comment by Roberrtt** [comment]
checked
