### ISSUE TITLE
Make all/send/receive/in progress in CAPS on wallet screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#150]
Please make all/send/receive/in progress in CAPS on wallet screen https://zpl.io/anq3dnQ
![image](https://user-images.githubusercontent.com/47353570/87150366-918f1380-c2ba-11ea-8f76-43e3d1bdc7c1.png)

https://zpl.io/V0jo5kx
![image](https://user-images.githubusercontent.com/47353570/87150696-3dd0fa00-c2bb-11ea-8688-353d35728b17.png)

Also on UTXO screen

**Comment by Sergei-Beam** [comment]
@iscander01 According to @dariatarakanova 's comment in the description we should make all tabs names CAPS on UTXO screen

On full
![image](https://user-images.githubusercontent.com/44496108/122292128-5059a780-cefe-11eb-9162-a701a8afa768.png)
and compact modes
![image](https://user-images.githubusercontent.com/44496108/122292282-7f701900-cefe-11eb-8a10-d0215c00b442.png)

**Comment by Sergei-Beam** [comment]
checked
