### ISSUE TITLE
Rename "Logout" to "Lock Wallet"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#151]
Rename "Logout" to "Lock Wallet" https://zpl.io/bJ0BNAE  

icons here - https://zpl.io/VDdg1KO

![image](https://user-images.githubusercontent.com/47353570/87151163-0747af00-c2bc-11ea-87d5-bc02be014a4e.png)

**Comment by Roberrtt** [comment]
Change icon for Lock Wallet button  and make 'W' a capital letter 
![Screenshot_291](https://user-images.githubusercontent.com/50007056/121528408-1b33ed80-ca04-11eb-9a36-1963600a6bdb.png)

**Comment by Roberrtt** [comment]
checked
