### ISSUE TITLE
Receive - big screen (before address book)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#172]
Designs: https://zpl.io/br36M1r

1) Reegular tx https://zpl.io/aX785LK
![image](https://user-images.githubusercontent.com/47353570/116710278-3c072d00-a9da-11eb-927e-9fbc29fb5d33.png)

2) Max privacy tx https://zpl.io/bl3EM81
![image](https://user-images.githubusercontent.com/47353570/116710364-58a36500-a9da-11eb-8455-158344235478.png)

3) Address details https://zpl.io/bW8JjK1
![image](https://user-images.githubusercontent.com/47353570/116710398-62c56380-a9da-11eb-90ec-8979f6b48948.png)

**Comment by Roberrtt** [comment]
2 - Max Privacy doesn't work, need to discuss 
3 - There're no "address details " on receive screen

**Comment by Sergei-Beam** [comment]
Note: 
in addition to maximum privacy, need to check the generation of the default address

after check, need to close the next ticket
https://github.com/BeamMW/beam/issues/1807

**Comment by dariatarakanova** [comment]
@gingervik duplicate of https://github.com/BeamMW/web-wallet/issues/79
