### ISSUE TITLE
Send - big screen (simplified)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#173]
Designs: https://zpl.io/bARpl8n

1) Please chnage button "add all" to "max" 
![image](https://user-images.githubusercontent.com/47353570/116714676-ab7f1b80-a9de-11eb-8388-d376a1f5b7ff.png)

2) Empty screen https://zpl.io/bz3e6G7
![image](https://user-images.githubusercontent.com/47353570/116714747-bf2a8200-a9de-11eb-85a5-808e714fc746.png)

3) Max Privacy https://zpl.io/bARplXn
![image](https://user-images.githubusercontent.com/47353570/116714801-c6519000-a9de-11eb-9154-46466f864488.png)

4) Regular https://zpl.io/254vpK8
![image](https://user-images.githubusercontent.com/47353570/116714826-cd789e00-a9de-11eb-83c6-c79287855f65.png)

5) Conatct https://zpl.io/ag3dkLO
![image](https://user-images.githubusercontent.com/47353570/116713339-5c84b680-a9dd-11eb-986e-a5345fff942e.png)

6) Confirmation https://zpl.io/2GjvAYd
![image](https://user-images.githubusercontent.com/47353570/116713364-64dcf180-a9dd-11eb-9d1f-6398b3f89da3.png)

7) Address details https://zpl.io/2j3xMXx
![image](https://user-images.githubusercontent.com/47353570/116713446-7625fe00-a9dd-11eb-9ec8-bf5c56726531.png)

**Comment by Roberrtt** [comment]
1 - Please change button "add max" to "max"
3,4,5,7 - There're no "address details"  and contact
6- Add Transaction Type  and center the text  to Confirmation screen
![Screenshot_324](https://user-images.githubusercontent.com/50007056/122351848-39936f00-cf57-11eb-9ae4-6ebfc4e8a7e0.png)

**Comment by iscander01** [comment]
1, 6 - done
3,4,5,7 there is no data in wallet API for "address details" and this version of the design is simplified (without contacts)

**Comment by KatsiarynaV** [comment]
1. The “Transaction type” field should be under the “Send to” field
![01](https://user-images.githubusercontent.com/68267190/124110429-e1895c00-da70-11eb-9917-7941aa9c0c23.jpg)
![11](https://user-images.githubusercontent.com/68267190/124110558-054ca200-da71-11eb-9e50-f2cfef96ebf4.jpg)
2. On the Confirmation screen remove the text for max privacy and offline transaction type
![05](https://user-images.githubusercontent.com/68267190/124111506-09c58a80-da72-11eb-9383-885172d4b7d4.jpg)
![06](https://user-images.githubusercontent.com/68267190/124111512-0a5e2100-da72-11eb-8474-175e0254cb58.jpg)
3. When inserting own address and switching to the offline on the confirmation screen the transaction type is displayed incorrectly
![17](https://user-images.githubusercontent.com/68267190/124126483-60879000-da83-11eb-8391-6d3317a09966.jpg)
4. Remove the blank space on the confirmation screen (when address is short)
![18](https://user-images.githubusercontent.com/68267190/124127117-03400e80-da84-11eb-9ffd-fa04b3cdbe74.jpg)
5. Change the text in the “Comment” field to “Comments are local and won’t be shared”. And make texts for this field and the “Send to” field  in italics
![09](https://user-images.githubusercontent.com/68267190/124111627-2a8de000-da72-11eb-8133-f6e93b450778.jpg)
![10](https://user-images.githubusercontent.com/68267190/124111632-2bbf0d00-da72-11eb-8a61-8f1062035616.jpg)
6. Align the "max" button and the arrow; currency selection and the amount field
![14](https://user-images.githubusercontent.com/68267190/124123082-84e16d80-da7f-11eb-8b5f-ceb9c723a3f4.jpg)
![15](https://user-images.githubusercontent.com/68267190/124123086-86129a80-da7f-11eb-9706-3db556d0be75.jpg)
7. When the “Send” screen is empty the fee should be 0 and the remaining should be equal to the available balance
![02](https://user-images.githubusercontent.com/68267190/124112737-447bf280-da73-11eb-897a-d4ba3a076c31.jpg)
![12](https://user-images.githubusercontent.com/68267190/124112756-4cd42d80-da73-11eb-80e2-e22837eaba23.jpg)
8. When inserting  SBBS address the 'transaction type' switcher shouldn't appear
![16](https://user-images.githubusercontent.com/68267190/124125581-75175880-da82-11eb-9ec9-cfa5a3fc73b6.jpg)

**Comment by dariatarakanova** [comment]
@gingervik 
this is the duplicate of https://github.com/BeamMW/web-wallet/issues/84
