### ISSUE TITLE
Add ability to switch between assets

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet-angular#187]
Need to add the ability to switch between assets to make able to sort transaction list by selected asset as on Desktop UI

WEB:
![image](https://user-images.githubusercontent.com/44496108/122288991-e2f84780-cefa-11eb-956a-6a8405284cc4.png)

Desktop UI:
![image](https://user-images.githubusercontent.com/44496108/122289561-877a8980-cefb-11eb-8c47-93361cc34bb0.png)
![image](https://user-images.githubusercontent.com/44496108/122289582-8e090100-cefb-11eb-9350-8ece9a14203d.png)

**Comment by dariatarakanova** [comment]
close as agreed with @gingervik
