### ISSUE TITLE
Security mode on wallet screen

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#2]

**Comment by VladislavKulyba** [comment]
Amounts are shown insecurity mode for fullscreen
![Snag_1655962](https://user-images.githubusercontent.com/51320829/80103815-33397b00-857e-11ea-8dd1-34ca5ea42699.png)

**Comment by dariatarakanova** [comment]
please add "eye" icons https://zpl.io/bzZPNJM

**Comment by VladislavKulyba** [comment]
1. In the status bar should be only one symbol of security mode according to design: https://zpl.io/beJx74D
2. The status should be shown with its own colour in security mode.
![Snag_1da2b15](https://user-images.githubusercontent.com/51320829/80977180-0a8e6c80-8e2d-11ea-9866-4137c8e515d4.png)

**Comment by VladislavKulyba** [comment]
Amount is shown for full list of transactions (after you press "Show all" button) for security mode.
Please, hide amount as it done for main screen
![Snag_81d5bb](https://user-images.githubusercontent.com/51320829/81388666-4a9d6a00-9121-11ea-99b0-75ac70687dbc.png)

**Comment by VladislavKulyba** [comment]
Checked
