### ISSUE TITLE
Long name asset

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/web-wallet-angular#202]
We need to shorten the name of long assets .
- asset name does not fit in the table
- in the transaction list
- in asset information
- on the send screen
- send confirmation
- receive screen

![Screenshot_348](https://user-images.githubusercontent.com/50007056/122759533-b8174600-d2a2-11eb-9a47-45ffcdaabaae.png)
![Screenshot_349](https://user-images.githubusercontent.com/50007056/122759540-b9e10980-d2a2-11eb-9835-407d7f5d1462.png)
![Screenshot_350](https://user-images.githubusercontent.com/50007056/122759910-2cea8000-d2a3-11eb-9477-987359a4284a.png)

**Comment by AndreyDyakonov** [comment]
1) If we want sent assets (with name is long and all letter are capital) that name do not fit in "sent" tab 

![1](https://user-images.githubusercontent.com/85252690/124118461-0a621f00-da7a-11eb-8cea-b4857bccf555.jpg)

2) If we want sent assets (with name is long and all letter are capital) and we don't have enough assets that name do not fit in "amount" tab 

![2](https://user-images.githubusercontent.com/85252690/124118473-0f26d300-da7a-11eb-82c4-d7732fae6494.jpg)

3) If we click button "balance" and then click button "asset info" we don't see all information

![31](https://user-images.githubusercontent.com/85252690/124118490-12ba5a00-da7a-11eb-838d-96c869368ca0.jpg)

look like this "asset info" in desktop wallet 

![32](https://user-images.githubusercontent.com/85252690/124118643-3aa9bd80-da7a-11eb-86c5-666ecce164db.png)
