### ISSUE TITLE
Send screen - change design (not a lot changes)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#35]
If there is **no possible** to add outgoing address on Send screen please change design according to this https://zpl.io/VD9m3Mr

if there is **possible** to add outgoing address on Send screen please change design according to this  https://zpl.io/2Z13dld

**Comment by sinaizd** [comment]
this version was implemented.

> if there is possible to add outgoing address on Send screen please change design according to this https://zpl.io/2Z13dld

>
