### ISSUE TITLE
Add possibility to copy address on Addresses screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#38]
Please add possibility to copy address on Addresses screen:
- by clicking with right button on mouse (the same as on desktop wallet)
- by clicking on action menu (3 dots)
https://zpl.io/blEey0v

**Comment by sinaizd** [comment]
@iscander01 this point not work.
> by clicking on action menu (3 dots)

> 
@dariatarakanova this point cannot be implemented on the web-wallet.

> by clicking with right button on mouse (the same as on desktop wallet)

> 
Think about other possibilities to copy the address  or leave only one possibility : 
-by clicking on action menu (3 dots)

**Comment by VladislavKulyba** [comment]
checked
