### ISSUE TITLE
Addresses screen - contacts list empty

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#39]
If there is no contacts please add icon and text according to design
https://zpl.io/an4zNek

For "My expired addresses" please use text "Your addresses list is empty"

**Comment by sinaizd** [comment]
Need to place the icon in accordance with the design, and replace it with the correct one.
![image](https://user-images.githubusercontent.com/45556620/79847798-e496b000-83c8-11ea-9aa7-014c5305f112.png)

**Comment by VladislavKulyba** [comment]
checked
