### ISSUE TITLE
Fix position for dropdown lists on Settings screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#41]
Dropdown list should be just below the item
https://zpl.io/boeEB3g

![image](https://user-images.githubusercontent.com/47353570/75984086-70747b80-5ef2-11ea-86a9-d9b49256f257.png)

**Comment by sinaizd** [comment]
please, fix according to design.
Actual:
![image](https://user-images.githubusercontent.com/45556620/79756292-19e8c280-8323-11ea-8989-376528f7b9bd.png)
design:
https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5e15fcbb588e1355afe151c8
![image](https://user-images.githubusercontent.com/45556620/79756334-253bee00-8323-11ea-8e34-fe00dc6d4658.png)

**Comment by sinaizd** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/79992177-d8d7e600-84bb-11ea-951a-6921442e537e.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/79992255-e9885c00-84bb-11ea-849e-793b9e4573da.png)

**Comment by VladislavKulyba** [comment]
checked
