### ISSUE TITLE
Add action menu to top bar on full version

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#44]
Please add this menu
https://zpl.io/V4xN36p

![image](https://user-images.githubusercontent.com/47353570/75987949-7cb00700-5ef9-11ea-82dc-fa337bba7e7c.png)

**Comment by VladislavKulyba** [comment]
Remove "Full view" line from action menu for fullscreen mode
![Snag_b93813](https://user-images.githubusercontent.com/51320829/79854180-bc5f7f00-83d1-11ea-8f14-036ccdd6042b.png)

**Comment by VladislavKulyba** [comment]
Checked
