### ISSUE TITLE
Errors do not highlighted (tested on password)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#46]
I type password with error but it doesn't highlight with red color

example: https://zpl.io/Vkv9ekG

**Comment by VladislavKulyba** [comment]
Highlighting doesn't disappear after deleting symbols of incorrect password 
Steps: 
1. Print  wrong password
2. Press "open your wallet" button
3. Delete symbols
Actual: incorrect password is still highlighting
Expected: incorrect password isn't shown
![Snag_1bbfd8f](https://user-images.githubusercontent.com/51320829/79768122-ffb6e080-8332-11ea-9664-68dcf57b715b.png)

**Comment by VladislavKulyba** [comment]
The "incorrect password" isn't shown only if all the symbols had been deleted. Please, do it as 
for the desktop version:
[2020-05-04_17-53-08.zip](https://github.com/BeamMW/web-wallet/files/4575358/2020-05-04_17-53-08.zip)

**Comment by VladislavKulyba** [comment]
It's done only for login screen. For other fields which require password should be done as for login screen.
Please, do it for all screens which require password (name of screen or popup/picture/comment with same issue):
1. Seed verification popup
![Snag_c83849](https://user-images.githubusercontent.com/51320829/81797291-3ee1e700-9517-11ea-8ef2-f495e66134d1.png)
https://github.com/BeamMW/web-wallet/issues/46#issuecomment-616620955
2. Change password popup
![Snag_cc6522](https://user-images.githubusercontent.com/51320829/81797760-e101cf00-9517-11ea-925e-0a7c77d66dad.png)
https://github.com/BeamMW/web-wallet/issues/46#issuecomment-623513211
3. Remove current wallet popup
![Snag_ce37cf](https://user-images.githubusercontent.com/51320829/81797991-27efc480-9518-11ea-9954-532520653257.png)
https://github.com/BeamMW/web-wallet/issues/46#issuecomment-616620955
4. Transaction confirmation popup on sender screen
![Snag_d490bf](https://user-images.githubusercontent.com/51320829/81798815-207ceb00-9519-11ea-968c-68b518eacbbb.png)
https://github.com/BeamMW/web-wallet/issues/46#issuecomment-616620955

**Comment by VladislavKulyba** [comment]
Checked
