### ISSUE TITLE
Send screen - make input address line longer

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#47]
If there is no QR code - make the line longer. So it should be the same space from left and right side

<img width="373" alt="Снимок экрана 2020-03-05 в 16 19 03" src="https://user-images.githubusercontent.com/47353570/75991399-19c16e80-5eff-11ea-83f4-5492448ee667.png">

**Comment by Roberrtt** [comment]
The address isn't fully inserted
![Screenshot_211](https://user-images.githubusercontent.com/50007056/80074189-7b8e7400-8551-11ea-9a83-0b4cc494e8c6.png)

**Comment by VladislavKulyba** [comment]
checked
