### ISSUE TITLE
Fix text color and add icon on Privacy Move on UTXO screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#50]
When privacy mode is on there is the dark text and no icon

design: https://zpl.io/bL0o1gY
<img width="373" alt="Снимок экрана 2020-03-05 в 16 20 51" src="https://user-images.githubusercontent.com/47353570/75991913-de736f80-5eff-11ea-897d-e4c1b054b87e.png">

**Comment by VladislavKulyba** [comment]
checked
