### ISSUE TITLE
No seed phrase when create new wallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#51]
<img width="373" alt="Снимок экрана 2020-03-05 в 16 17 48" src="https://user-images.githubusercontent.com/47353570/75992128-327e5400-5f00-11ea-9d7c-466f66effec9.png">

**Comment by Roberrtt** [comment]
not done, for not full screen
[Video.zip](https://github.com/BeamMW/web-wallet/files/4503701/Video.zip)

**Comment by Roberrtt** [comment]
checked
