### ISSUE TITLE
Create action menu (3 dots)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#53]
Please create action menu for both versions (full and small).

Please remove Settings from the general menu (small) and left side menu (full)
![image](https://user-images.githubusercontent.com/47353570/76205133-4f699e80-6202-11ea-935f-d5e0ff6479ad.png)

small: https://zpl.io/VD9k08g
full: https://zpl.io/V4xN36p

**Comment by VladislavKulyba** [comment]
If you press on action menu when burger menu is opened, action menu will be hiden behind main menu.
![Snag_13a0f2b](https://user-images.githubusercontent.com/51320829/79980831-5d226d00-84ac-11ea-8535-78d8e76c4630.png)

**Comment by VladislavKulyba** [comment]
Please add this separetion line for Security Mode
![Snag_daf3b2](https://user-images.githubusercontent.com/51320829/80954466-1a468a80-8e06-11ea-9782-d96944040e48.png)
@dariatarakanova Please, update information in design. This mode should be renamed to Security mode as it's done in wallet

**Comment by VladislavKulyba** [comment]
Checked
