### ISSUE TITLE
Add action menu on transactions screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#54]
Please make it as on-hover on small screen. On full screen it can be all time
small: https://zpl.io/bL0kzLm
full: https://zpl.io/25vkR9e

**Comment by VladislavKulyba** [comment]
Not done for small screen
![Snag_e0aba0](https://user-images.githubusercontent.com/51320829/80091556-f499c580-8569-11ea-9636-bf8195b5a3bf.png)

**Comment by VladislavKulyba** [comment]
1. This menu should be done only for transactions with status "Sent"
![Snag_1138cd5](https://user-images.githubusercontent.com/51320829/80096094-b86a6300-8571-11ea-9b30-31b14226474c.png)
Right now it also show for different statuses:
![Snag_11209cf](https://user-images.githubusercontent.com/51320829/80095956-7ccf9900-8571-11ea-8cbe-46ced4b29eed.png)
For other statuses should be only "Delete transaction" and "Cancel Transaction"
2. Shape of menu should be rounded according to design
![Snag_11643b7](https://user-images.githubusercontent.com/51320829/80096723-ae952f80-8572-11ea-8eaa-83925d26243e.png)

**Comment by VladislavKulyba** [comment]
> Not done for small screen
> ![Snag_e0aba0](https://user-images.githubusercontent.com/51320829/80091556-f499c580-8569-11ea-9636-bf8195b5a3bf.png)

It will be released only for full list of transactions.

**Comment by VladislavKulyba** [comment]
Checked
