### ISSUE TITLE
Fix wallet creation process design on small view

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#57]

**Comment by Roberrtt** [comment]
The small screen starts with the wallet login screen
![Screenshot_182](https://user-images.githubusercontent.com/50007056/79789225-8af39e80-8352-11ea-84a2-b83afdeee056.png)

**Comment by Roberrtt** [comment]
1. The start screen hasn't 'restore wallet' button 
https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5de775ed015f1e5727140dfe

2. After "seed phrase" screen if we click complete verification, there is no popup "save seed phrase"
https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5df3b57b4ee38d47bc3f4ac5

3. If you go back from the password screen, there is no pop-up "Return to seed phrase'
https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5df3b57ca42831493d0c8db9

**Comment by VladislavKulyba** [comment]
1. not relevant
2-3. done and checked
