### ISSUE TITLE
Tables sorting not working

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#59]

**Comment by Roberrtt** [comment]
1.Please make the sorting work when you first click on the fields on the address page.
[Video.zip](https://github.com/BeamMW/web-wallet/files/4508902/Video.zip)
2.On UTXO page  sorting doesn't work

**Comment by Roberrtt** [comment]
Please make the sorting work when you first click on the fields on the  wallet-send tab
![Screenshot_198](https://user-images.githubusercontent.com/50007056/79977644-488fa600-84a7-11ea-989e-2df88b6ecc10.png)

**Comment by VladislavKulyba** [comment]
1. Please, highlight the name of default sorting column 
![Snag_155e13d](https://user-images.githubusercontent.com/51320829/81176928-8cf26a00-8fae-11ea-9dfa-c05d9e600f8b.png)
2. After clicking on column few seconds later sorting will be changed. it's reproduce when there are equal values
[2020-05-06_15-35-19.zip](https://github.com/BeamMW/web-wallet/files/4586729/2020-05-06_15-35-19.zip)

**Comment by Roberrtt** [comment]
checked
