### ISSUE TITLE
Utxo list and payment proof details in transaction table

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#63]

**Comment by Roberrtt** [comment]
We only show the details and copy buttons for transactions with the sent status
![Screenshot_194](https://user-images.githubusercontent.com/50007056/79858719-8671c900-83d8-11ea-9a78-19186361f1bb.png)
![Screenshot_193](https://user-images.githubusercontent.com/50007056/79858722-87a2f600-83d8-11ea-9a98-f48e91097085.png)

**Comment by Roberrtt** [comment]
1. The address of the sender and receiver are different if we check
![Screenshot_214](https://user-images.githubusercontent.com/50007056/80090840-ce275a80-8568-11ea-8c01-34db7a8438f9.png)

2. There are no  payment proof details for sent transaction  in small screen 
https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5de7cc1dbd578153b04a4c79

**Comment by VladislavKulyba** [comment]
> 1. The address of the sender and receiver are different if we check
>    ![Screenshot_214](https://user-images.githubusercontent.com/50007056/80090840-ce275a80-8568-11ea-8c01-34db7a8438f9.png)
> 2. There are no  payment proof details for sent transaction  in small screen
>    https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5de7cc1dbd578153b04a4c79

1. Will be done in the next sprint
2. Checked
