### ISSUE TITLE
Add design for "Full view" link on Login and Create wallet screens

### ISSUE THREAD

**Issue by iscander01** [BeamMW/web-wallet-angular#66]

**Comment by dariatarakanova** [comment]
Added header to the screens:
https://app.zeplin.io/project/5de7758cdc60cf574430983c/dashboard?seid=5dfa61bcea9fee1d08eb9ce1 

please pay attention: https://zpl.io/bA11Wwe - here I reduce blocks height for seed words.. please also do it if needed

please place logo in header only on screens where is no another logo 
![image](https://user-images.githubusercontent.com/47353570/79963548-3a835a80-8492-11ea-8113-3dff50acbc65.png)

**Comment by VladislavKulyba** [comment]
Checked
