### ISSUE TITLE
Add text "Scalable confidential cryptocurrency" on all login/restore screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#69]
We need to have text "Scalable confidential cryptocurrency" on all login/restore screens.

![image](https://user-images.githubusercontent.com/47353570/79847683-b74a0200-83c8-11ea-92d3-fbae07528aa4.png)

**Comment by sinaizd** [comment]
text more bold in the web wallet than on the design.
![image](https://user-images.githubusercontent.com/45556620/80072228-a0351c80-854e-11ea-8a01-7bac48cae61c.png)
![image](https://user-images.githubusercontent.com/45556620/80072285-b216bf80-854e-11ea-9b1c-1f7cf5595d7d.png)

**Comment by VladislavKulyba** [comment]
"Scalable confidential cryptocurrency" is missed for login screen in extension view
![Snag_f12035](https://user-images.githubusercontent.com/51320829/80956233-7ced5580-8e09-11ea-9676-04f83e89b8fe.png)

**Comment by dariatarakanova** [comment]
For extension view:

Please leave the logo big on first login screen https://zpl.io/VQ555ZP and https://zpl.io/bA19nR6
On other login/restore screen make it smaller
https://zpl.io/aMggOPd
https://zpl.io/VKzw6BR
https://zpl.io/bzZZgJM

**Comment by VladislavKulyba** [comment]
Checked
