### ISSUE TITLE
Buttons on login/restore screens should be at the same height

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#70]
Example: 
![image](https://user-images.githubusercontent.com/47353570/79848431-bebddb00-83c9-11ea-9bec-4cf6110018c6.png)

https://zpl.io/anJ4p5A
https://zpl.io/amZN9Z3

Exception: restore screens with comments
https://zpl.io/a70NOzK and https://zpl.io/2jJxQrq

![image](https://user-images.githubusercontent.com/47353570/79848254-84543e00-83c9-11ea-8016-8efc0cf0cbc9.png)

**Comment by VladislavKulyba** [comment]
Please, lower this to the button
![Snag_195ebe4](https://user-images.githubusercontent.com/51320829/81818371-a0657e00-9536-11ea-9fd5-32189e9addd0.png)

**Comment by VladislavKulyba** [comment]
Checked
