### ISSUE TITLE
Send screen - Add more space between "change" (outgoing address) and "hide/show" arrow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#72]
Design: https://zpl.io/VO8yEd1
![image](https://user-images.githubusercontent.com/47353570/79850463-a56a5e00-83cc-11ea-942a-c451ed872bab.png)

**Comment by sinaizd** [comment]
the arrow needs to be raised up a little
![image](https://user-images.githubusercontent.com/45556620/80087956-87cffc80-8564-11ea-92f2-e483484b80e0.png)

**Comment by Roberrtt** [comment]
checked
