### ISSUE TITLE
Transaction confirmation should include transaction info, not only password

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#73]
https://zpl.io/VOG81nL

please pay attention all popups on full screen view should be same wight (as on design)

**Comment by sinaizd** [comment]
not fix
![image](https://user-images.githubusercontent.com/45556620/80090106-a8e61c80-8567-11ea-8c58-3aef2c307706.png)

**Comment by VladislavKulyba** [comment]
Checked
