### ISSUE TITLE
Add "close" icon on some popups

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#76]
Please add "close" icon on popups if there are no any buttons
example:
https://zpl.io/Vk6vl8M , https://zpl.io/agJdK9R , 

or you chose between two actions and there is no "cancel" or "back" button
example: 
https://zpl.io/bJR4lZ6

**Comment by VladislavKulyba** [comment]
checked

**Comment by VladislavKulyba** [comment]
Please, add "close" icon to payment proof popup
![Snag_1133ed4](https://user-images.githubusercontent.com/51320829/82050366-b3a45500-96c0-11ea-8433-cc87b9fbc0da.png)

**Comment by VladislavKulyba** [comment]
checked
