### ISSUE TITLE
Settings - dns/ip should have a name

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#78]
![image](https://user-images.githubusercontent.com/47353570/79950308-8c6eb500-847f-11ea-8def-bd357c3a6d21.png)

**Comment by sinaizd** [comment]
Aligned, please.
![image](https://user-images.githubusercontent.com/45556620/81053569-f51d4f00-8ecd-11ea-8c0b-d433e1aea160.png)

**Comment by VladislavKulyba** [comment]
Checked
