### ISSUE TITLE
Add on-hover effect for text in settings and dropdown options

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#80]
Please make on-hover text items - highligted on **settings** and **dropdown** options

as here https://app.zeplin.io/project/5de7758cdc60cf574430983c/screen/5de7cc1ff6ae1b56baa42205/

not it is added only for settings sections (general, server, privacy etc)

**Comment by VladislavKulyba** [comment]
The letters and icons should be highlighted too
![Snag_193015f](https://user-images.githubusercontent.com/51320829/81073928-0035a680-8ef1-11ea-89ea-9f9a4a700787.png)

**Comment by VladislavKulyba** [comment]
checked
