### ISSUE TITLE
Settings - report a problem. Links inside don't work

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#81]
Report a problem links - dont' click
![image](https://user-images.githubusercontent.com/47353570/79951354-3438b280-8481-11ea-9218-43c0223a65fe.png)

**Comment by VladislavKulyba** [comment]
![Snag_2c6c3bf](https://user-images.githubusercontent.com/51320829/86338161-aa644d00-bc5a-11ea-8ba8-ca20f1847c90.png)

This link should lead to https://github.com/BeamMW

**Comment by VladislavKulyba** [comment]
checked
