### ISSUE TITLE
Update icon on "open your wallet" button

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#82]
Please update icon on "open your wallet" button:

full: https://zpl.io/amZN9Z3
small: https://zpl.io/aMggOPd

**Comment by Roberrtt** [comment]
Reduce the circle in the icon slightly on full and small screen.
![Screenshot_271](https://user-images.githubusercontent.com/50007056/81056990-403a6080-8ed4-11ea-8ad7-27f1980718aa.png)

**Comment by VladislavKulyba** [comment]
Checked
