### ISSUE TITLE
Wallet doesn't create again after using "Remove current wallet" in settings.

### ISSUE THREAD

**Issue by sinaizd** [BeamMW/web-wallet-angular#83]
Str:
1. Install expansion web-wallet
2. Create a new wallet.
3. Go to Settings.
4. Use function"Remove current wallet".
5. Again create a new wallet.
Expected: new wallet is created.
Actual: new wallet doesn't create.
[glcbdcgeepbblgenidkdjlnddmomgdom-1587625577947.log](https://github.com/BeamMW/web-wallet/files/4520820/glcbdcgeepbblgenidkdjlnddmomgdom-1587625577947.log)

**Comment by VladislavKulyba** [comment]
Sometimes this behaviour is reproduced:
[2020-05-04_14-57-27.zip](https://github.com/BeamMW/web-wallet/files/4574669/2020-05-04_14-57-27.zip)
There is another situation when it leads to create screen again after passing the password screen:
[2020-05-04_15-05-58.zip](https://github.com/BeamMW/web-wallet/files/4574684/2020-05-04_15-05-58.zip)
logs:  [jkenjmlecacidpglojikcgkobfekbbcp-1588597825653.log](https://github.com/BeamMW/web-wallet/files/4574825/jkenjmlecacidpglojikcgkobfekbbcp-1588597825653.log)

**Comment by VladislavKulyba** [comment]
Checked
