### ISSUE TITLE
Add Privacy Mode to full view wallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#84]
Please add it ti the overflow menu
https://zpl.io/V4xN36p

**Comment by VladislavKulyba** [comment]
1. In the status bar should be only one symbol of security mode according to design: https://zpl.io/beJx74D
2. Status should be shown with its own colour in security mode.
![Snag_1d696b4](https://user-images.githubusercontent.com/51320829/80976760-7e7c4500-8e2c-11ea-9348-19d1ad8cdf0c.png)

**Comment by VladislavKulyba** [comment]
Checked
