### ISSUE TITLE
Issues with the Addresses screen 

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#88]
1. Wallet created with address, which has wrong expiration time
![Snag_da8325](https://user-images.githubusercontent.com/51320829/80198064-3d17b880-8628-11ea-8a29-5071c9844d74.png)
2. Addresses don't expire automatically
3. Action menu in Addresses screen doesn't work at all
4. Address which created on receive screen with different comment hasn't it name in the addresses screen
![Snag_e60d01](https://user-images.githubusercontent.com/51320829/80199458-017dee00-862a-11ea-8fca-b71e62ed8d6e.png)

**Comment by iscander01** [comment]
not relevant
