### ISSUE TITLE
Wallet logs can't be saved

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#89]
Pressing on this button doesn't lead to saving the logs
![Snag_15de8a9](https://user-images.githubusercontent.com/51320829/80210356-49a60c00-863c-11ea-80d8-ca71ad762111.png)

**Comment by iscander01** [comment]
Need to save logs (client side) from current session

**Comment by VladislavKulyba** [comment]
> Need to save logs (client side) from current session

Checked
