### ISSUE TITLE
Restore issues

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet-angular#90]
1. "Restore wallet or create a new one" button isn't available
![Snag_1759842](https://user-images.githubusercontent.com/51320829/80212307-e74f0a80-863f-11ea-8e25-3faa164d600e.png)
Notice: Also it should be renamed from "Restore wallet or create a new one" to "Restore wallet" for thos screen.
@dariatarakanova please, change it also in design: https://zpl.io/a7xgqKp
2. There isn't button for login page in fullscreen. It should be named "Restore  wallet or create a new one" like in design: https://zpl.io/bJ0YGAD
![Snag_17b0aca](https://user-images.githubusercontent.com/51320829/80212748-bcb18180-8640-11ea-9c7f-24a42eccef20.png)
3. There aren't restore buttons for extension view:
![Snag_21c870f](https://user-images.githubusercontent.com/51320829/80213000-2e89cb00-8641-11ea-8248-b75b0d502014.png)
Design: https://zpl.io/bzR7Qll
https://zpl.io/2vo37gr

**Comment by iscander01** [comment]
not relevant
