### ISSUE TITLE
fix the design of dropdown menu on full screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#91]
Please fix the design of dropdown menu on full screen:
- change icons for privacy mode
- fix paddings for logout item
https://zpl.io/V4xN36p

here is "privacy mode is off" icon https://zpl.io/2GvqKJE

![image](https://user-images.githubusercontent.com/47353570/80953652-9f30a480-8e04-11ea-8080-c98e8e6a5859.png)

**Comment by VladislavKulyba** [comment]
checked
