### ISSUE TITLE
Change "Secondary currency" in general setting to "Show amounts in"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet-angular#92]
Please change "Secondary currency" in general setting to "Show amounts in" and add the text when it was updated
https://zpl.io/VD9QOgv

![image](https://user-images.githubusercontent.com/47353570/80954362-e703fb80-8e05-11ea-9222-e5d3cf7c5914.png)

**Comment by VladislavKulyba** [comment]
This data isn't actual
![Snag_6ba715](https://user-images.githubusercontent.com/51320829/81386160-3bb4b880-911d-11ea-8831-a805e3cd6259.png)

**Comment by VladislavKulyba** [comment]
checked
